resources:
- name: concourse-config
  type: git
  source:
    private_key: {{concourse-config-private-key}}
    uri: {{concourse-config-git-url}}

- name: concourse-release
  type: github-release
  source:
    repository: concourse
    user: concourse

- name: concourse-deployment
  type: bosh-deployment
  source:
    target: {{concourse-deployment-bosh-target}}
    username: {{concourse-deployment-bosh-username}}
    password: {{concourse-deployment-bosh-password}}
    deployment: {{concourse-deployment-bosh-deployment}}
    ignore_ssl: {{concourse-deployment-bosh-ignore-ssl}}

- name: stemcell
  type: bosh-io-stemcell
  source:
    name: {{stemcell}}

jobs:
- name: deploy-concourse
  serial: true
  plan:
  - aggregate:
    - get: concourse-release
      trigger: false
      params:
        globs:
        - concourse-*.tgz
        - garden-linux-*.tgz
    - get: concourse-config
      trigger: true
    - get: stemcell
      trigger: false
  - put: concourse-deployment
    params:
      manifest: {{concourse-config-manifest-location}}
      releases:
        - concourse-release/concourse-*.tgz
        - concourse-release/garden-linux-*.tgz
      stemcells:
        - stemcell/*.tgz
